#ifndef JOYSTICK_BUTTON_SHEET_H
#define JOYSTICK_BUTTON_SHEET_H

// HMI button mappings
#define LINEAR_MOTION_BUTTON 1
#define SEMI_CUBIC_MOTION_BUTTON 2
#define DRIVER_ARM_DOWN_BUTTON 4
#define SHOOTER_FLUSH_TWO_BUTTON 3
#define SHOOTER_FLUSH_ONE_BUTTON 5

#define DRIVER_ARM_UP_BUTTON 6
#define TOGGLE_BRAKE_FIRST_BUTTON 7
#define TOGGLE_BRAKE_SECOND_BUTTON 8
#define DRIVER_STATION_TOGGLE 9
#define TANK_MODE_BUTTON 10
#define FIELD_MODE_BUTTON 11
#define ROBOT_MODE_BUTTON 12


/* 
 * HMI button mappings
*/

// I put these in button number order, so we can see what buttons are used nor not
#define MOVE_TO_SHOOTER_BUTTON 1
#define COLLECTOR_ON_BUTTON 2
#define SHOOTER_SPEED_DOWN_BUTTON 3
#define OPERATOR_ARM_DOWN_BUTTON 4
#define SHOOTER_SPEED_UP_BUTTON 5
#define OPERATOR_ARM_UP_BUTTON 6
#define PURGE_COLLECTOR_BUTTON 7
#define COLLECTOR_ALWAYS_ON_BUTTON 8
#define SHOOTER_OFF_BUTTON 9
#define SHOOTER_ON_BUTTON 10
#define SHOOTER_FINE_ADJ_BUTTON 11
#define TURRET_MANUAL_BUTTON 12


#endif
